# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AlignParameters:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Encoding:
  Enabled: true

  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed