# encoding: utf-8
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AlignParameters:
  Enabled: true

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 300

Style/Encoding:
  Enabled: true

  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'

  Include:
    - '**/Gemfile'
    - '**/Rakefile'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
