AlignParameters:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Encoding:
  Enabled: false

  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
