development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_development
  username:  postgres #mine is visitmeet
  password: nepal
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_test
  username:  postgres #mine is visitmeet
  password: nepal
  pool: 5

production:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: visitmeet_production
  pool:     5
  template: template0

staging:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: visitmeet_staging
  username: postgres #mine is visitmeet
  password: bandana
  pool:     5
  template: template0
