development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_development
  pool: 5
  username: visitor
  password: bandmember
test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_test
  pool: 5
  username: visitor
  password: bandmember

production:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: visitmeet_production
  pool:     5
  username: visitor
  password: changemenow
  template: template0
