development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmee_development
  pool: 5
  username: visitmeet
  password: bandana
test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmee_test
  pool: 5
  username: visitmeet
  password: bandana

production:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: visitmeet_production
  pool:     5
  username: visitmeet
  password:
  template: template0
