development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_development
  pool: 5
test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_test
  pool: 5
production:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: visitmeet_production
  pool:     5
  template: template0
