development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_development
  username:  visitmeet #change back to postgres for pull requests
  password: bandana
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: visitmeet_test
  username:  visitmeet #change back to postgres for pull requests
  password: bandana
  pool: 5

production:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: visitmeet_production
  pool:     5
  template: template0

staging:
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  database: visitmeet_staging
  username: visitmeet #change back to postgres for pull requests
  password: bandana
  pool:     5
  template: template0
