# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  # TODO: 20160409 : Mandril will cease being a free service in April 2016.
  # change email_provider_username to google using bishisht@google.com
  # set variable in local and heroku environments
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: example.com
  # stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  # stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  secret_key_base: 931741d8b0d2baa83978355be1c382000b738193345fd001aa07d17d8669bb1513c019840e39c2320742138563b6da3c519d302ad8778310029e8c1835fa2165

test:
  domain_name: example.com
  secret_key_base: 6d1ef5c210624318304552d43412ab8440259b2e44429c5af841090fb8256816ad5224a778848989fe262ab3a0c1460aee7b7f0f79255a0d6f27b99e6ae8abd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  # TODO: 20160409 : see note in development
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  # stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  # stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

